// LOCALHOST 
// PLANTS
### Get all songs GET http://localhost:8080/plants

### Get song by id GET http://localhost:8080/plants/65a60dddc88ca384b22d9e9d

### Create song POST http://localhost:8080/plants

{
  {
    "name": "Burbank Russet Potato",
    "scientificName": "Solanum tuberosum",
    "categoryId": "65f507ffbff26de7fd7c9e25",
    "coldestZone": 2,
    "warmestZone": 10,
    "colors": [
      "White"
    ],
    "height": 30,
    "space": 22,
    "daysToGermination": 28,
    "daysToFlower": 75,
    "daysToHarvest": 130
  }
}

### PUT plant PUT http://localhost:8080/plants/6220bcb39cd507e920c75a0b

{
  {
    "name": "Burbank Russet Potato",
    "scientificName": "Solanum tuberosum",
    "categoryId": "65f507ffbff26de7fd7c9e25",
    "coldestZone": 3,
    "warmestZone": 10,
    "colors": [
      "White"
    ],
    "height": 30,
    "space": 22,
    "daysToGermination": 28,
    "daysToFlower": 75,
    "daysToHarvest": 130
  }
}

### DELETE plant DELETE http://localhost:8080/plants/6220b775099269ff7b31ceab

// Categories
### Get all categories GET http://localhost:8080/category

### Get category by id GET http://localhost:8080/category/65a60dddc88ca384b22d9e9d

### Create category POST http://localhost:8080/category

{
    "name": "Shrubery"
}

### PUT category PUT http://localhost:8080/category/6220bcb39cd507e920c75a0b

{
    "name": "Shrub"
}

### DELETE category DELETE http://localhost:8080/category/6220b775099269ff7b31ceab


// Cares
### Get all cares GET http://localhost:8080/care

### Get care by id GET http://localhost:8080/care/65a60dddc88ca384b22d9e9d

### Create care POST http://localhost:8080/care

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late Summer or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### PUT care PUT http://localhost:8080/care/6220bcb39cd507e920c75a0b

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late winter or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### DELETE care DELETE http://localhost:8080/care/6220b775099269ff7b31ceab

// Care Types
### Get all caretypes GET http://localhost:8080/caretype

### Get caretype by id GET http://localhost:8080/caretype/65a60dddc88ca384b22d9e9d

### Create caretype POST http://localhost:8080/caretype

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late Summer or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### PUT caretype PUT http://localhost:8080/caretype/6220bcb39cd507e920c75a0b

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late winter or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### DELETE caretype DELETE http://localhost:8080/caretype/6220b775099269ff7b31ceab


// PRODUCTION Deploy 

// PLANTS
### Get all songs GET https://gardengrow.onrender.com/plants

### Get song by id GET https://gardengrow.onrender.com/plants/65a60dddc88ca384b22d9e9d

### Create song POST https://gardengrow.onrender.com/plants

{
  {
    "name": "Burbank Russet Potato",
    "scientificName": "Solanum tuberosum",
    "categoryId": "65f507ffbff26de7fd7c9e25",
    "coldestZone": 2,
    "warmestZone": 10,
    "colors": [
      "White"
    ],
    "height": 30,
    "space": 22,
    "daysToGermination": 28,
    "daysToFlower": 75,
    "daysToHarvest": 130
  }
}

### PUT plant PUT https://gardengrow.onrender.com/plants/6220bcb39cd507e920c75a0b

{
  {
    "name": "Burbank Russet Potato",
    "scientificName": "Solanum tuberosum",
    "categoryId": "65f507ffbff26de7fd7c9e25",
    "coldestZone": 3,
    "warmestZone": 10,
    "colors": [
      "White"
    ],
    "height": 30,
    "space": 22,
    "daysToGermination": 28,
    "daysToFlower": 75,
    "daysToHarvest": 130
  }
}

### DELETE plant DELETE https://gardengrow.onrender.com/plants/6220b775099269ff7b31ceab

// Categories
### Get all categories GET https://gardengrow.onrender.com/category

### Get category by id GET https://gardengrow.onrender.com/category/65a60dddc88ca384b22d9e9d

### Create category POST https://gardengrow.onrender.com/category

{
    "name": "Shrubery"
}

### PUT category PUT https://gardengrow.onrender.com/category/6220bcb39cd507e920c75a0b

{
    "name": "Shrub"
}

### DELETE category DELETE https://gardengrow.onrender.com/category/6220b775099269ff7b31ceab


// Cares
### Get all cares GET https://gardengrow.onrender.com/care

### Get care by id GET https://gardengrow.onrender.com/care/65a60dddc88ca384b22d9e9d

### Create care POST https://gardengrow.onrender.com/care

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late Summer or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### PUT care PUT https://gardengrow.onrender.com/care/6220bcb39cd507e920c75a0b

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late winter or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### DELETE care DELETE https://gardengrow.onrender.com/care/6220b775099269ff7b31ceab

// Care Types
### Get all caretypes GET https://gardengrow.onrender.com/caretype

### Get caretype by id GET https://gardengrow.onrender.com/caretype/65a60dddc88ca384b22d9e9d

### Create caretype POST https://gardengrow.onrender.com/caretype

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late Summer or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### PUT caretype PUT https://gardengrow.onrender.com/caretype/6220bcb39cd507e920c75a0b

{
    "plantId": "65f2708ad22b76d6ea65e7f8",
    "careTypeId": "65f50992bff26de7fd7c9e26",
    "description": "Prune in late winter or early spring. Remove dead parts. Remove any dead branches and canes. Prune broken or unhealthy branches. Prune diseased or damaged branches back to healthy wood. Remove crossed branches. Clip away branches that cross through the center of the plant. Prevent rubbing branches."
}

### DELETE caretype DELETE https://gardengrow.onrender.com/caretype/6220b775099269ff7b31ceab


